version: '3.8'

services:
  react-crm:
    build: .
    command: npm start
    container_name: react-crm
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_GOOGLE_CLIENT_ID=your_google_client_id.apps.googleusercontent.com

